sudo: false
language: node_js
node_js:
  - "6"

branches:
  only:
    - master

# cache:
#   directories:
#     - node_modules

install:
  - npm install -g npm

  # Output our current versions for debugging
  - node --version
  - npm --version

  # Install our package dependencies
  - npm install --production

script:
  - npm run eslint
